# Generated by Django 5.0.1 on 2024-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='special'),
        ),
    ]
