# Generated by Django 5.0.1 on 2024-01-28 19:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
