# Generated by Django 5.0.1 on 2024-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
